"""Unit tests for the 3MF upload path (upload.py).

The 3MF files are built in each test with zipfile: a real slice_info.config
layout and a G-code header, no toolpath. What is under test is everything
around the parser: file-name checks, the size cap, staging and the TTL, the
per-model plan, re-validation on start, and the per-model upload commands.
"""
import sys
import zipfile
from io import BytesIO
from pathlib import Path
from unittest.mock import AsyncMock, Mock

import pytest

project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from tests.ha_mocks import mock_homeassistant

mock_homeassistant()

from flashforge.threemf import PrinterFamily, parse_3mf

from custom_components.flashforge import upload
from custom_components.flashforge.const import DOMAIN
from custom_components.flashforge.job import JobStartError
from custom_components.flashforge.upload import (
    PLAN_AD5X_STATION,
    PLAN_CREATOR5,
    PLAN_PLAIN,
    FlashForgeUploadView,
    UploadError,
    UploadStore,
    async_stage_upload,
    async_upload_and_print,
    get_store,
    model_mismatch,
    printer_family,
    sanitize_file_name,
    threemf_to_file_entry,
    upload_plan,
    ws_upload_discard,
    ws_upload_start,
)

ENTRY_ID = "entry-1"

GCODE = """; HEADER_BLOCK_START
; generated by Flash Studio 1.7.6 on 2026-06-25 at 16:37:56
; total layer number: 27
; HEADER_BLOCK_END
; estimated printing time (normal mode) = 28m 18s
; EXECUTABLE_BLOCK_START
G28
"""


def make_3mf(
    filaments=((1, "PLA", "#FF0000"), (2, "PETG", "#000000")),
    *,
    model="Flashforge-Creator-5-Pro",
    plates=(1,),
) -> bytes:
    """A sliced 3MF using the given (filament id, material, color) filaments."""
    filament_xml = "".join(
        f'<filament id="{fid}" type="{material}" color="{color}" used_m="1.0" used_g="3.5" />'
        for fid, material, color in filaments
    )
    slice_info = (
        '<?xml version="1.0" encoding="UTF-8"?><config><plate>'
        '<metadata key="index" value="1"/>'
        f'<metadata key="printer_model_id" value="{model}"/>'
        '<metadata key="prediction" value="1698"/><metadata key="weight" value="7.0"/>'
        f"{filament_xml}"
        '<warning msg="bed_temperature_too_high_than_filament" level="3" error_code="1000C001" />'
        "</plate></config>"
    )
    buffer = BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("Metadata/slice_info.config", slice_info)
        for index in plates:
            archive.writestr(f"Metadata/plate_{index}.gcode", GCODE)
            archive.writestr(f"Metadata/plate_{index}.png", b"\x89PNG-thumb")
    return buffer.getvalue()


def make_machine_info(
    *,
    family="creator5_pro",
    slots=((1, "PLA", "#FF0000"), (2, "PETG", "#000000")),
    state="ready",
):
    """Machine info for a printer family with the given (slot, material, color) slots."""
    info = Mock()
    info.is_creator5 = family in ("creator5", "creator5_pro")
    info.is_creator5_pro = family == "creator5_pro"
    info.is_ad5x = family == "ad5x"
    info.is_pro = family in ("5m_pro", "creator5_pro")
    info.machine_state = Mock(value=state)
    info.matl_station_info.slot_infos = [
        Mock(
            slot_id=slot_id,
            has_filament=material is not None,
            material_name=material or "",
            material_color=color or "",
        )
        for slot_id, material, color in slots
    ]
    return info


def make_hass(machine_info=None, client=None):
    async def run_in_executor(func, *args):
        return func(*args)

    hass = Mock()
    hass.data = {
        DOMAIN: {
            ENTRY_ID: {
                "name": "Test Printer",
                "client": client or make_client(),
                "coordinator": Mock(
                    data=machine_info or make_machine_info(),
                    async_request_refresh=AsyncMock(),
                ),
            }
        }
    }
    hass.async_add_executor_job = run_in_executor
    hass.async_create_task = Mock()
    return hass


def make_client():
    client = Mock()
    client.job_control.upload_file_creator5 = AsyncMock(return_value=True)
    client.job_control.start_creator5_job = AsyncMock(return_value=True)
    client.job_control.upload_file_ad5x = AsyncMock(return_value=True)
    client.job_control.upload_file = AsyncMock(return_value=True)
    return client


async def chunks_of(data: bytes, size: int = 1000):
    for start in range(0, len(data), size):
        yield data[start : start + size]


@pytest.fixture(autouse=True)
def isolated_store(tmp_path, monkeypatch):
    """Give every test its own scratch directory."""
    monkeypatch.setattr(upload.tempfile, "gettempdir", lambda: str(tmp_path))


async def stage(hass, data=None, name="print.3mf"):
    return await async_stage_upload(hass, ENTRY_ID, name, chunks_of(data or make_3mf()))


def connection():
    conn = Mock()
    conn.send_result = Mock()
    conn.send_error = Mock()
    return conn


# --------------------------------------------------------------------------- #
# Pure helpers
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("name", "expected"),
    [
        ("benchy.3mf", "benchy.3mf"),
        ("Benchy.gcode.3MF", "Benchy.gcode.3MF"),
        ("Billy-Knöpfe.3mf", "Billy-Knöpfe.3mf"),
        ("benchy.gcode", None),
        ("../evil.3mf", None),
        ("sub\\evil.3mf", None),
        (".hidden.3mf", None),
        ("nul\0.3mf", None),
        ("", None),
        (None, None),
        ("a" * 252 + ".3mf", None),
    ],
)
def test_sanitize_file_name(name, expected):
    assert sanitize_file_name(name) == expected


@pytest.mark.parametrize(
    ("family", "expected"),
    [
        ("creator5_pro", PrinterFamily.CREATOR_5_PRO),
        ("creator5", PrinterFamily.CREATOR_5),
        ("ad5x", PrinterFamily.AD5X),
        ("5m_pro", PrinterFamily.ADVENTURER_5M_PRO),
        ("5m", PrinterFamily.ADVENTURER_5M),
    ],
)
def test_printer_family(family, expected):
    assert printer_family(make_machine_info(family=family)) is expected


def test_model_mismatch_names_the_file_model(tmp_path):
    path = tmp_path / "a.3mf"
    path.write_bytes(make_3mf(model="Flashforge-AD5X"))
    info = parse_3mf(path)

    assert model_mismatch(info, make_machine_info(family="creator5_pro")) == "Flashforge-AD5X"
    assert model_mismatch(info, make_machine_info(family="ad5x")) is None


def test_model_mismatch_ignores_unknown_ids(tmp_path):
    path = tmp_path / "a.3mf"
    path.write_bytes(make_3mf(model="Some Other Printer"))

    assert model_mismatch(parse_3mf(path), make_machine_info(family="ad5x")) is None


def test_threemf_to_file_entry_keeps_slicer_tool_ids(tmp_path):
    path = tmp_path / "a.3mf"
    path.write_bytes(make_3mf(filaments=((3, "PLA", "#00FF00"),)))

    entry = threemf_to_file_entry(parse_3mf(path))

    assert entry["file_name"] == "a.3mf"
    assert entry["printing_time"] == 1698
    assert entry["total_filament_weight"] == 7.0
    assert entry["tool_count"] == 1
    assert entry["use_matl_station"] is False
    assert entry["tool_datas"] == [
        {
            "tool_id": 2,
            "material_name": "PLA",
            "material_color": "#00FF00",
            "filament_weight": 3.5,
            "slot_id": 0,
        }
    ]


def _entry(tool_ids=(0, 1)):
    return {
        "file_name": "f.3mf",
        "tool_datas": [{"tool_id": tool_id} for tool_id in tool_ids],
    }


def _slots(machine_info):
    return upload.slots_to_list(machine_info)


def test_plan_creator5():
    info = make_machine_info(family="creator5")
    assert upload_plan(info, _slots(info), _entry()) == PLAN_CREATOR5


def test_plan_creator5_needs_a_station():
    info = make_machine_info(family="creator5_pro", slots=())
    with pytest.raises(UploadError, match="not reporting its Material Station"):
        upload_plan(info, [], _entry())


def test_plan_creator5_needs_tool_data():
    info = make_machine_info(family="creator5_pro")
    with pytest.raises(UploadError, match="does not say which filaments"):
        upload_plan(info, _slots(info), _entry(tool_ids=()))


def test_plan_rejects_filament_five_and_up():
    info = make_machine_info(family="ad5x")
    with pytest.raises(UploadError, match="uses filament 5"):
        upload_plan(info, _slots(info), _entry(tool_ids=(0, 4)))


def test_plan_ad5x_with_station():
    info = make_machine_info(family="ad5x")
    assert upload_plan(info, _slots(info), _entry()) == PLAN_AD5X_STATION


def test_plan_ad5x_without_station_is_plain():
    info = make_machine_info(family="ad5x", slots=())
    assert upload_plan(info, [], _entry()) == PLAN_PLAIN


@pytest.mark.parametrize("family", ["5m", "5m_pro"])
def test_plan_5m_series_is_plain_even_with_many_tools(family):
    info = make_machine_info(family=family, slots=())
    assert upload_plan(info, [], _entry(tool_ids=(0, 1, 5))) == PLAN_PLAIN


# --------------------------------------------------------------------------- #
# Staging
# --------------------------------------------------------------------------- #


async def test_stage_returns_the_dialog_payload():
    hass = make_hass()

    payload = await stage(hass)

    assert payload["requires_matching"] is True
    assert payload["file"]["file_name"] == "print.3mf"
    assert [tool["tool_id"] for tool in payload["file"]["tool_datas"]] == [0, 1]
    assert [slot["slot_id"] for slot in payload["slots"]] == [1, 2]
    assert payload["suggested_mappings"] == [
        {
            "tool_id": 0,
            "slot_id": 1,
            "material_name": "PLA",
            "tool_material_color": "#FF0000",
            "slot_material_color": "#FF0000",
        },
        {
            "tool_id": 1,
            "slot_id": 2,
            "material_name": "PETG",
            "tool_material_color": "#000000",
            "slot_material_color": "#000000",
        },
    ]
    assert payload["suggestion_complete"] is True
    assert payload["thumbnail"] is not None
    assert payload["model_mismatch"] is None
    assert payload["slicer_warnings"][0].startswith("The current hot bed temperature")

    staged = get_store(hass).get(payload["upload_id"], ENTRY_ID)
    assert staged is not None
    assert staged.path.read_bytes() == make_3mf()
    assert staged.expiry is not None


async def test_stage_on_a_5m_needs_no_matching():
    hass = make_hass(make_machine_info(family="5m_pro", slots=()))

    payload = await stage(hass, make_3mf(model="Flashforge-Adventurer-5M-Pro"))

    assert payload["requires_matching"] is False
    assert payload["suggested_mappings"] == []
    assert payload["suggestion_complete"] is False


async def test_stage_reports_a_model_mismatch():
    hass = make_hass(make_machine_info(family="ad5x"))

    payload = await stage(hass, make_3mf(model="Flashforge-Creator-5-Pro"))

    assert payload["model_mismatch"] == "Flashforge-Creator-5-Pro"


async def test_stage_unknown_printer():
    hass = make_hass()
    with pytest.raises(UploadError) as excinfo:
        await async_stage_upload(hass, "other", "a.3mf", chunks_of(make_3mf()))
    assert excinfo.value.status == 404


async def test_stage_refuses_non_3mf_names():
    with pytest.raises(UploadError, match="Only sliced .3mf"):
        await stage(make_hass(), name="print.gcode")


async def test_stage_enforces_the_size_cap(monkeypatch):
    monkeypatch.setattr(upload, "MAX_UPLOAD_BYTES", 100)
    hass = make_hass()

    with pytest.raises(UploadError) as excinfo:
        await stage(hass)

    assert excinfo.value.status == 413
    store = get_store(hass)
    assert len(store) == 0
    assert list(store.directory.iterdir()) == []


async def test_stage_refuses_an_empty_file():
    hass = make_hass()
    with pytest.raises(UploadError, match="empty"):
        await async_stage_upload(hass, ENTRY_ID, "a.3mf", chunks_of(b""))


async def test_stage_refuses_a_project_file_and_cleans_up():
    hass = make_hass()

    with pytest.raises(UploadError, match="holds no sliced G-code"):
        await stage(hass, make_3mf(plates=()))

    assert list(get_store(hass).directory.iterdir()) == []


async def test_stage_refuses_multiple_plates():
    with pytest.raises(UploadError, match="single plate"):
        await stage(make_hass(), make_3mf(plates=(1, 2)))


async def test_stage_refuses_a_file_that_is_not_a_zip():
    with pytest.raises(UploadError, match="not a readable 3MF"):
        await stage(make_hass(), b"not a zip at all")


async def test_stage_refuses_an_unmatchable_file_on_a_creator5():
    hass = make_hass(make_machine_info(family="creator5", slots=()))
    with pytest.raises(UploadError, match="Material Station"):
        await stage(hass)
    assert list(get_store(hass).directory.iterdir()) == []


async def test_stage_caps_waiting_uploads(monkeypatch):
    monkeypatch.setattr(upload, "MAX_STAGED_UPLOADS", 2)
    hass = make_hass()
    await stage(hass)
    await stage(hass)

    with pytest.raises(UploadError) as excinfo:
        await stage(hass)
    assert excinfo.value.status == 429


async def test_expired_uploads_are_swept(monkeypatch):
    hass = make_hass()
    first = await stage(hass)
    store = get_store(hass)
    store._staged[first["upload_id"]].created -= upload.STAGE_TTL_SECONDS + 1

    second = await stage(hass)

    assert store.get(first["upload_id"], ENTRY_ID) is None
    assert store.get(second["upload_id"], ENTRY_ID) is not None
    assert len(list(store.directory.iterdir())) == 1


async def test_orphans_from_a_previous_run_are_removed(tmp_path):
    leftover = tmp_path / upload.STAGE_DIR_NAME / "old"
    leftover.mkdir(parents=True)
    (leftover / "old.3mf").write_bytes(b"x")

    await stage(make_hass())

    assert not leftover.exists()


def test_store_only_returns_uploads_to_their_own_printer(tmp_path):
    store = UploadStore(tmp_path)
    store.add(upload.StagedUpload("u1", ENTRY_ID, tmp_path / "a.3mf", Mock(), {}))

    assert store.get("u1", ENTRY_ID) is not None
    assert store.get("u1", "someone-else") is None


def test_uploads_being_sent_do_not_expire(tmp_path):
    store = UploadStore(tmp_path)
    staged = upload.StagedUpload("u1", ENTRY_ID, tmp_path / "a.3mf", Mock(), {})
    staged.created -= upload.STAGE_TTL_SECONDS + 1
    staged.in_progress = True
    store.add(staged)

    assert store.expired() == []


# --------------------------------------------------------------------------- #
# Dispatch
# --------------------------------------------------------------------------- #


def _mapping(tool_id=0, slot_id=1):
    from flashforge.models import AD5XMaterialMapping

    return AD5XMaterialMapping(
        tool_id=tool_id,
        slot_id=slot_id,
        material_name="PLA",
        tool_material_color="#FF0000",
        slot_material_color="#FF0000",
    )


async def test_creator5_uploads_without_starting_then_starts_with_mappings(tmp_path):
    client = make_client()
    path = tmp_path / "a.3mf"

    await async_upload_and_print(
        client, PLAN_CREATOR5, path, leveling_before_print=True, mappings=[_mapping()]
    )

    params = client.job_control.upload_file_creator5.await_args.args[0]
    assert params.start_print is False
    assert params.use_matl_station is True
    assert params.gcode_tool_cnt == 1
    assert params.material_mappings is None
    start = client.job_control.start_creator5_job.await_args.args[0]
    assert start.file_name == "a.3mf"
    assert start.leveling_before_print is True
    assert [m.slot_id for m in start.material_mappings] == [1]


async def test_creator5_failed_upload_does_not_start(tmp_path):
    client = make_client()
    client.job_control.upload_file_creator5.return_value = False

    with pytest.raises(JobStartError, match="did not accept the upload"):
        await async_upload_and_print(
            client, PLAN_CREATOR5, tmp_path / "a.3mf", leveling_before_print=False,
            mappings=[_mapping()],
        )
    client.job_control.start_creator5_job.assert_not_awaited()


async def test_creator5_refused_start(tmp_path):
    client = make_client()
    client.job_control.start_creator5_job.return_value = False

    with pytest.raises(JobStartError, match="refused to start"):
        await async_upload_and_print(
            client, PLAN_CREATOR5, tmp_path / "a.3mf", leveling_before_print=False,
            mappings=[_mapping()],
        )


async def test_ad5x_station_uploads_and_starts_with_mappings(tmp_path):
    client = make_client()

    await async_upload_and_print(
        client, PLAN_AD5X_STATION, tmp_path / "a.3mf", leveling_before_print=False,
        mappings=[_mapping()],
    )

    params = client.job_control.upload_file_ad5x.await_args.args[0]
    assert params.start_print is True
    assert params.flow_calibration is False
    assert params.first_layer_inspection is False
    assert params.time_lapse_video is False
    assert len(params.material_mappings) == 1


async def test_plain_upload_starts_at_once(tmp_path):
    client = make_client()
    path = tmp_path / "a.3mf"

    await async_upload_and_print(
        client, PLAN_PLAIN, path, leveling_before_print=True, mappings=[]
    )

    client.job_control.upload_file.assert_awaited_once_with(str(path), True, True)


async def test_refused_plain_upload(tmp_path):
    client = make_client()
    client.job_control.upload_file.return_value = False

    with pytest.raises(JobStartError, match="did not accept"):
        await async_upload_and_print(
            client, PLAN_PLAIN, tmp_path / "a.3mf", leveling_before_print=False, mappings=[]
        )


async def test_library_exception_becomes_job_start_error(tmp_path):
    client = make_client()
    client.job_control.upload_file_ad5x.side_effect = OSError("network down")

    with pytest.raises(JobStartError, match="network down"):
        await async_upload_and_print(
            client, PLAN_AD5X_STATION, tmp_path / "a.3mf", leveling_before_print=False,
            mappings=[_mapping()],
        )


# --------------------------------------------------------------------------- #
# Websocket: start / discard
# --------------------------------------------------------------------------- #


def start_msg(upload_id, mappings=None, **extra):
    return {
        "id": 7,
        "type": "flashforge/upload/start",
        "entry_id": ENTRY_ID,
        "upload_id": upload_id,
        "leveling": False,
        "material_mappings": mappings if mappings is not None else [],
        **extra,
    }


async def test_start_sends_the_validated_mappings_and_cleans_up():
    client = make_client()
    hass = make_hass(client=client)
    payload = await stage(hass)
    conn = connection()

    await ws_upload_start(
        hass,
        conn,
        start_msg(
            payload["upload_id"],
            [{"tool_id": 0, "slot_id": 1}, {"tool_id": 1, "slot_id": 2}],
        ),
    )

    conn.send_error.assert_not_called()
    result = conn.send_result.call_args.args[1]
    assert result["started"] is True
    assert result["file_name"] == "print.3mf"
    start = client.job_control.start_creator5_job.await_args.args[0]
    assert [(m.tool_id, m.slot_id, m.material_name) for m in start.material_mappings] == [
        (0, 1, "PLA"),
        (1, 2, "PETG"),
    ]
    assert get_store(hass).get(payload["upload_id"], ENTRY_ID) is None
    hass.data[DOMAIN][ENTRY_ID]["coordinator"].async_request_refresh.assert_awaited()


async def test_start_refuses_a_skipped_matching_dialog():
    client = make_client()
    hass = make_hass(client=client)
    payload = await stage(hass)
    conn = connection()

    await ws_upload_start(hass, conn, start_msg(payload["upload_id"]))

    assert "needs its tools matched" in conn.send_error.call_args.args[2]
    client.job_control.upload_file_creator5.assert_not_awaited()
    # Still staged, so the user can fix the mapping and retry.
    assert get_store(hass).get(payload["upload_id"], ENTRY_ID) is not None


async def test_start_refuses_a_material_mismatch():
    client = make_client()
    hass = make_hass(client=client)
    payload = await stage(hass)
    conn = connection()

    await ws_upload_start(
        hass,
        conn,
        start_msg(
            payload["upload_id"],
            [{"tool_id": 0, "slot_id": 2}, {"tool_id": 1, "slot_id": 1}],
        ),
    )

    assert "Material mismatch" in conn.send_error.call_args.args[2]
    client.job_control.upload_file_creator5.assert_not_awaited()


async def test_start_on_a_5m_ignores_mappings():
    client = make_client()
    hass = make_hass(make_machine_info(family="5m", slots=()), client=client)
    payload = await stage(hass)
    conn = connection()

    await ws_upload_start(
        hass, conn, start_msg(payload["upload_id"], [{"tool_id": 0, "slot_id": 1}])
    )

    conn.send_error.assert_not_called()
    client.job_control.upload_file.assert_awaited_once()


async def test_start_refuses_while_the_printer_is_busy():
    client = make_client()
    hass = make_hass(make_machine_info(family="5m", slots=(), state="printing"), client=client)
    payload = await stage(hass)
    conn = connection()

    await ws_upload_start(hass, conn, start_msg(payload["upload_id"]))

    assert "The printer is printing" in conn.send_error.call_args.args[2]
    client.job_control.upload_file.assert_not_awaited()


async def test_start_of_an_expired_upload():
    conn = connection()
    await ws_upload_start(make_hass(), conn, start_msg("nope"))

    assert conn.send_error.call_args.args[1] == upload.ERR_UPLOAD_NOT_FOUND


async def test_start_refuses_an_upload_already_being_sent():
    hass = make_hass()
    payload = await stage(hass)
    get_store(hass).get(payload["upload_id"], ENTRY_ID).in_progress = True
    conn = connection()

    await ws_upload_start(hass, conn, start_msg(payload["upload_id"]))

    assert "already being sent" in conn.send_error.call_args.args[2]


async def test_failed_send_keeps_the_upload_for_a_retry():
    client = make_client()
    client.job_control.upload_file.return_value = False
    hass = make_hass(make_machine_info(family="5m", slots=()), client=client)
    payload = await stage(hass)
    conn = connection()

    await ws_upload_start(hass, conn, start_msg(payload["upload_id"]))

    conn.send_error.assert_called_once()
    staged = get_store(hass).get(payload["upload_id"], ENTRY_ID)
    assert staged is not None
    assert staged.in_progress is False


async def test_start_for_an_unknown_printer():
    conn = connection()
    msg = start_msg("x")
    msg["entry_id"] = "other"

    await ws_upload_start(make_hass(), conn, msg)

    assert conn.send_error.call_args.args[1] == upload.ERR_ENTRY_NOT_FOUND


async def test_discard_deletes_the_staged_file():
    hass = make_hass()
    payload = await stage(hass)
    staged = get_store(hass).get(payload["upload_id"], ENTRY_ID)
    conn = connection()

    await ws_upload_discard(
        hass, conn, {"id": 3, "entry_id": ENTRY_ID, "upload_id": payload["upload_id"]}
    )

    conn.send_result.assert_called_once_with(3, {})
    assert get_store(hass).get(payload["upload_id"], ENTRY_ID) is None
    assert not staged.path.parent.exists()


async def test_discard_of_another_printers_upload_is_ignored():
    hass = make_hass()
    payload = await stage(hass)
    conn = connection()

    await ws_upload_discard(
        hass, conn, {"id": 3, "entry_id": "other", "upload_id": payload["upload_id"]}
    )

    assert get_store(hass).get(payload["upload_id"], ENTRY_ID) is not None


# --------------------------------------------------------------------------- #
# HTTP view
# --------------------------------------------------------------------------- #


class FakePart:
    def __init__(self, name, *, text="", data=b"", filename=None):
        self.name = name
        self.filename = filename
        self._text = text
        self._data = data

    async def text(self):
        return self._text

    async def read_chunk(self, size):
        chunk, self._data = self._data[:size], self._data[size:]
        return chunk


class FakeReader:
    def __init__(self, parts):
        self._parts = list(parts)

    async def next(self):
        return self._parts.pop(0) if self._parts else None


def fake_request(parts):
    request = Mock()
    request.multipart = AsyncMock(return_value=FakeReader(parts))
    return request


async def test_view_stages_a_multipart_upload():
    hass = make_hass()
    view = FlashForgeUploadView(hass)

    response = await view.post(
        fake_request(
            [
                FakePart("entry_id", text=ENTRY_ID),
                FakePart("file", data=make_3mf(), filename="print.3mf"),
            ]
        )
    )

    assert response.status == 200
    assert response.body["requires_matching"] is True
    assert view.requires_auth is True


async def test_view_needs_the_entry_id_first():
    view = FlashForgeUploadView(make_hass())

    response = await view.post(
        fake_request([FakePart("file", data=make_3mf(), filename="print.3mf")])
    )

    assert response.status == 400
    assert "entry_id" in response.body["message"]


async def test_view_needs_a_file():
    view = FlashForgeUploadView(make_hass())

    response = await view.post(fake_request([FakePart("entry_id", text=ENTRY_ID)]))

    assert response.status == 400
    assert response.body["message"] == "No file was uploaded."


async def test_view_reports_upload_errors_with_their_status(monkeypatch):
    monkeypatch.setattr(upload, "MAX_UPLOAD_BYTES", 10)
    view = FlashForgeUploadView(make_hass())

    response = await view.post(
        fake_request(
            [
                FakePart("entry_id", text=ENTRY_ID),
                FakePart("file", data=make_3mf(), filename="print.3mf"),
            ]
        )
    )

    assert response.status == 413


async def test_view_hides_unexpected_errors():
    request = Mock()
    request.multipart = AsyncMock(side_effect=RuntimeError("boom"))

    response = await FlashForgeUploadView(make_hass()).post(request)

    assert response.status == 500
    assert response.body["message"] == "The upload failed."
